#assignment
print("       *")
print("      * *")
print("     *   *")
print("    *     *")
print("   *       *")
print("  *         *")
print(" *           *")
print("*             *")
print(" *           *")
print("  *         *")
print("   *       *")
print("    *     *")
print("     *   *")
print("      * *")
print("       *")